name: "Publish to pypi"
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Example for other repos:
      # - uses: Private-Crypto-Trading-Fund/midas-dev/.github/common_pypi@master
      #   …
      - uses: actions/checkout@v3  # For `./.github/` to exist.
      - uses: ./.github/common_pypi
        env:
          PYPI_PASSWORD: "${{ secrets.PYPI_TOKEN }}"
